### PR TITLE
Revert boo-boos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@domluna so sorry about this. I feel like quite the idiot. I had originally cloned the repo and forgot that since I am part of the udacity github org that any commits I made wouldn't go to my personal github but rather the real thing!! This should undo the changes I made. Again, so sorry about this and I feel very embarrassed lol.

**Comment by domluna** [comment]
haha, no problem

**Comment by Shmuelnaaman** [comment]
The file do not work for me  as it is now

**Comment by domluna** [comment]
@Shmuelnaaman should work now, there was some leftover json in the notebook from the last merge that it wasn't happy with.

**Pull request merged**
