### PR TITLE
Required Datasets and Models for classification

### PR DESCRIPTION
**Pull request by ManishEnishetty**
hello,
       We are working on traffic sign recognition .we have downloaded GTRSB(German traffic sign) but we are not able to get models  and also 'train.p' . What should be given in models path of your code for execution?
please let us know what should be given in models path.

### CODE REVIEW

**Comment by mvirgo** [comment]
I'm not sure what you mean by model path - this should be your trained model after building your neural network. The training data is [here](https://s3-us-west-1.amazonaws.com/udacity-selfdrivingcar/traffic-signs-data.zip).

In the future, you might instead open a similar question as an "Issue" - PRs are only for code you want to have us review to merge into the Udacity master.

**Comment by ManishEnishetty** [comment]
Hey Michael,
  We are working on video processing. Mainly on detection of traffic sign
in video . There are two stages in it.
1) Detection of sign in a frame
2) classification of sign using CNN.
 We are able to classify but first we couldn't detect the sign in a
frame.we have divided video into frames using python.
can you help us to detect the sign in the frame?
 We are ready to hear from you

**Comment by mvirgo** [comment]
Hi Manish - this project just focuses on the classification aspect. If you want to look into finding *where* in the frame a sign might be (if at all), I'd suggest looking into [YOLO](https://arxiv.org/abs/1506.02640), [SSD](https://arxiv.org/abs/1512.02325), or [Faster R-CNN](https://arxiv.org/abs/1506.01497). You should also try out Tensorflow's [Model Detection Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), which has some easy to deploy versions of the above.

**Comment by UAnjali** [comment]
Hi @ManishEnishetty 
Apologies for the delayed response. We hope that your issue is resolved. Feel free to suggest an update to the starter code. 
Happy Learning
Udacity

**Pull request closed without merging**
